language: python

sudo: false

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install codecov
  - pip install pytest-cov

script: py.test --cov=elizabeth/

after_success:
  codecov

deploy:
  provider: pypi
  user: $USER
  password: $PYPI_PASSWORD
  on:
    branch: master
    tags: true

notifications:
  email:
    on_success: never
    on_failure: change
